### ISSUE TITLE
java.lang.ClassCastException: net.openhft.smoothie.Segment63 cannot be cast to net.openhft.smoothie.Segment

### ISSUE THREAD

**Issue by noahtaylor** [TimeAndSpaceIO/SmoothieMap#5]
I am getting the following exception when I am running a unit test. Any ideas?

java.lang.ClassCastException: net.openhft.smoothie.Segment63 cannot be cast to net.openhft.smoothie.Segment
at net.openhft.smoothie.SmoothieMap.makeSegment(SmoothieMap.java:589)
at net.openhft.smoothie.SmoothieMap.initSegments(SmoothieMap.java:446)
at net.openhft.smoothie.SmoothieMap.(SmoothieMap.java:429)
at net.openhft.smoothie.SmoothieMap.(SmoothieMap.java:411)

**Comment by noahtaylor** [comment]
I should also mention this issue only occurs when running the build on TeamCity, I cannot reproduce the issue locally.

**Comment by noahtaylor** [comment]
Ok so I was able to address the issue by removing PowerMockRunner from my unit tests.  Not sure why that would have caused an issue.  Perhaps due to class loader being different?

**Comment by leventov** [comment]
This should now be fixed in SmoothieMap 2.0.1
